### ISSUE TITLE
¿Que ocurrio con este proyecto? 

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/enki#3]
....

**Comment by jobsamuel** [comment]
Por razones de disponibilidad, durante el año pasado, de los colaboradores principales, se decidió continuarlo durante el primer trimestre de este año. Si los planes cambian (si no se va a continuar), yo me encargaré de eliminar el repo :wink:

**Comment by Villanuevand** [comment]
Vamos a intentar que siga adelante, los responsables que armen un backlog de actividades a realizar y lo coloquen en algún sitio público para cuando alguien tenga un poco de tiempo ayude. Que nos muestren cual es su idea del proyecto
Las actividades ser actividades desde crear html, css y js... hasta no sé, crear una directiva, o algo más avanzado... 
Siempre pensando en el "Producto Mínimo Viable" ...

**Comment by jobsamuel** [comment]
Perfecto, entonces dedicaré parte de este próximo Sábado 23 a **revivir** el proyecto y hacer lo necesario para que otros miembros de la comunidad (y colaborares iniciales) se animen a colaborar y continuar, respectivamente.

**Comment by Villanuevand** [comment]
Si necesitas un poco de ayuda, no dudes en escribir....

**Comment by code-andres** [comment]
Bueno, el proyecto aún tiene futuro y tiempo para ser finalizado, el problema fue la disponibilidad...

Ya el Sábado me pongo con @jobsamuel para empezar con el proyecto otra vez.

**Comment by Villanuevand** [comment]
Lo importante, es ir desarrollando poco a poco... Nínguno de nosotros tiene disponibilidad al 10% del tiempo para este proyecto... No hace falta reuniones largas, lo que hace falta es que tengan la idea clara, e ir creando muchas tareas pequeñas. 

Le comentaba a @jobsamuel  que tengamos en mente siempre el tener el "producto mínimo viable"... Y poco a poco ir iterandolo para mejorarlo. 

Que ese esa el norte a seguir muchachos, cualquier cosa, estoy a la orden para organizar, desarrollar, revisar, corregir y demás actividades...

**Comment by Villanuevand** [comment]
Alguna novedad de este proyecto?

**Comment by jobsamuel** [comment]
La novedad es: @abr4xas revivió el proyecto. Así que cerraré éste _issue_ :sunglasses:
